### ISSUE TITLE
Bad resource computation for pods.

### ISSUE THREAD

**Issue by lebrisg** [etopeter/kubectl-view-utilization#21] opened 2019-02-12 09:49 UTC
Test is done on a namespace with the following used resources:
infra: hawkular-cassandra-1-rlcm8 / cpu: - / mem: 1G-2G
infra: hawkular-metrics-8cjz9         / cpu: - / mem: 1500M-2500M
infra: heapster-2s7jk                      / cpu: - / mem: 937500k-3750M

The template used for the pod computation gives the following intermediate result:
infra nod1.example.com                1G
infra inf.example.com         1500M
infra nod2.example.com                937500k

The final result is:
NAMESPACE          CPU    MEMORY
infra                       939         0

The correct result should be:
NAMESPACE          CPU    MEMORY
infra                         0          3.4G

**Comment by etopeter** [comment] 2019-02-14 02:08
Thanks for submitting this issue. It will help greatly if you could provide output of this command

```shell
kubectl get pod --all-namespaces -o=go-template --template='{{range .items}}{{ $n:=.metadata.namespace }}{{range .spec.containers}}{{ $n }}{{"\t"}}{{ if .resources.requests.cpu }}{{ .resources.requests.cpu }}{{end}}{{"\t"}}{{ if .resources.requests.memory }}{{ .resources.requests.memory }}{{end}}{{"\n"}}{{end}}{{end}}' 
```

I'm suspecting that requests could be in different unit that is not parsed correctly.

**Comment by etopeter** [comment] 2019-02-14 17:10
@lebrisg please check newest [release v0.1.4](https://github.com/etopeter/kubectl-view-utilization/releases/tag/v0.1.4). This release should resolve your issue.

**Comment by lebrisg** [comment] 2019-02-15 18:12
I executed the required command and got the following result:
default 100m    256Mi
default
default 100m    256Mi
glusterfs       100m    100Mi
glusterfs       100m    100Mi
glusterfs       100m    100Mi
glusterfs
guestbook
guestbook
kube-service-catalog
kube-service-catalog
kube-system
kube-system
kube-system
nvidia-device-plugin
openshift-ansible-service-broker
openshift-infra         1G
openshift-infra         1500M
openshift-infra
openshift-infra         937500k
openshift-node
openshift-node
openshift-node
openshift-node
openshift-node
openshift-sdn   100m    300Mi
openshift-sdn   100m    300Mi
openshift-sdn   100m    300Mi
openshift-sdn   100m    300Mi
openshift-sdn   100m    300Mi
openshift-sdn   100m    200Mi
openshift-sdn   100m    200Mi
openshift-sdn   100m    200Mi
openshift-sdn   100m    200Mi
openshift-sdn   100m    200Mi
openshift-template-service-broker
openshift-web-console   100m    100Mi

I used the latest version of kubectl-view-utilization available but with a 3.10 version of OpenShift (<1.12 of Kubernetes).

**Comment by etopeter** [comment] 2019-02-16 17:05
Thank you for submitting output of the template command. I can see the problem is with lower case `k` in memory output. I will update this issue with the fix for that.

**Comment by etopeter** [comment] 2019-02-16 18:58
@lebrisg the fix for this issue is now in master branch. It would be great if you could confirm that this fixes your issue.
I changed test to us lower case `k` in memory request just like in your cluster output.

**Comment by etopeter** [comment] 2019-02-24 02:06
The fix for this issue is now in latest release [v0.2.0](https://github.com/etopeter/kubectl-view-utilization/releases/tag/v0.2.0)
I'm closing this issue. Please feel free to reopen if this you still see this bug after upgrading to latest version.

**Closed by etopeter** 2019-02-24 02:06 UTC
Labels: bug
